(TeX-add-style-hook
 "DefinicionesYPropiedades"
 (lambda ()
   (LaTeX-add-index-entries
    "\\texttt{sonIncidentes}"
    "\\texttt{esLazo}"
    "\\texttt{entorno}"
    "\\texttt{grado}"
    "\\texttt{esAislado}"
    "\\texttt{esRegular}"
    "\\texttt{valenciaMin}"
    "\\texttt{valenciaMax}"
    "\\texttt{esSimple}"
    "\\texttt{secuenciaGrados}"
    "\\texttt{secuenciaGrafica}"
    "\\texttt{esSubgrafo}"
    "\\texttt{esSubconjunto}"
    "\\texttt{esSubgrafoMax}"
    "\\texttt{esSubgrafoPropio}"
    "\\texttt{prop$\\_$LemaApretonDeManos}"
    "\\texttt{prop$\\_$HavelHakimi}"
    "\\texttt{eliminaArista}"
    "\\texttt{eliminaVertice}"
    "\\texttt{sumaArista}"
    "\\texttt{sumaVertice}"
    "\\texttt{prop$\\_$completos}"
    "\\texttt{sumaGrafos}"
    "\\texttt{complementario}"))
 :latex)

